# Generated by Django 3.2.9 on 2021-11-08 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Magasin', '0002_auto_20211108_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='personne',
        ),
        migrations.AddField(
            model_name='demande',
            name='motif_demande',
            field=models.CharField(default=datetime.datetime(2021, 11, 8, 16, 10, 9, 972375, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiel',
            name='demandes',
            field=models.ManyToManyField(through='Magasin.Demande', to='Magasin.Personne'),
        ),
    ]
